[package]
name = "v821-avaota-f1"
version = "0.1.0"
publish = false
default-run = "usb-uart"
edition.workspace = true
license.workspace = true
repository.workspace = true

[target.'cfg(target_os = "none")'.dependencies]
allwinner-rt = { path = "../../allwinner-rt", default-features = false, features = ["v821-mcu", "panic-halt"] }

[lib]
name = "v821_avaota_f1"
test = true
bench = false

[[bin]]
name = "usb-uart"
test = false
bench = false

[[bin]]
name = "uart-demo"
test = false
bench = false
