//! Allwinner D1 ROM runtime.
//!
//! # Usage
//!
//! Here's an sample usage of this crate:
//!
//! ```no_run
//! use allwinner_rt::{entry, Clocks, Peripherals};
//!
//! #[entry]
//! fn main(p: Peripherals, c: Clocks) {
//!     /* code */
//! }
//! ```
#![no_std]

#[macro_use]
mod macros;

mod boot0;
pub use boot0::EgonHead;

#[cfg(any(feature = "nezha", feature = "lichee"))]
mod mctl;
#[cfg(any(feature = "nezha", feature = "lichee"))]
/// Dram initializing function.
pub use mctl::init as dram_init;

pub use allwinner_rt_macros::entry;

pub mod arch {
    pub mod andes_a27l2;
    pub mod riscv_fpu;
    pub mod thead_c906;
}

pub mod soc {
    pub mod d1;
    pub mod v821;
    pub mod v853;
}

#[allow(unused)]
#[rustfmt::skip]
unsafe extern "Rust" {
    // This symbol is generated by `#[entry]` macro in allwinner-rt or other ROM-stage software packages.
    fn main();
}

cfg_if::cfg_if! {
    if #[cfg(feature = "d1")] {
        pub use {
            self::arch::thead_c906::start,
            self::soc::d1::{__rom_init_params, Peripherals, Clocks},
        };
    } else if #[cfg(feature = "v821")] {
        pub use {
            self::arch::andes_a27l2::start,
            self::soc::v821::{__rom_init_params, Peripherals, Clocks},
        };
    } else {
        pub struct Peripherals {}
        pub struct Clocks {}
        #[doc(hidden)]
        pub fn __rom_init_params() -> (Peripherals, Clocks) {
            (Peripherals {}, Clocks {})
        }
        pub fn start() {}
    }
}
