[package]
name = "rfel"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.6.6", features = ["derive"] }
clap-verbosity-flag = "3.0.4"
env_logger = "0.11.11"
futures = "0.3.34"
log = "0.4.34"
num-traits = "0.2.19"
nusb = "0.2.7"
object = "0.40.0"
project-root = "0.2.2"
same-file = "1.0.6"
thiserror = "2.0.20"
