[package]
name = "rfel-payload"
version = "0.0.0"
publish = false
edition.workspace = true
license = "MIT"
repository.workspace = true
autobins = false

[dependencies]
panic-never = "0.1.0"
rfel-payload-macros = { path = "macros" }

[features]
default = []
d1 = []
f101 = []
v821 = []

[[bin]]
name = "read32"
path = "src/bin/read32.rs"
test = false
bench = false

[[bin]]
name = "write32"
path = "src/bin/write32.rs"
test = false
bench = false

[[bin]]
name = "fence_i_f101"
path = "src/bin/fence_i_f101.rs"
required-features = ["f101"]
test = false
bench = false

[[bin]]
name = "copy_v821"
path = "src/bin/copy_v821.rs"
required-features = ["v821"]
test = false
bench = false

