[package]
name = "rfel-payload"
version = "0.0.0"
publish = false
edition.workspace = true
license = "MIT"
repository.workspace = true
autobins = false

[dependencies]
allwinner-hal = { path = "../../allwinner-hal" }
panic-never = "0.1.0"
rfel-payload-macros = { path = "macros" }

[[bin]]
name = "ddr-d1"
path = "src/bin/ddr_d1.rs"
test = false
bench = false

[[bin]]
name = "ddr-f101"
path = "src/bin/ddr_f101.rs"
test = false
bench = false

[[bin]]
name = "ddr-v821"
path = "src/bin/ddr_v821.rs"
test = false
bench = false

[[bin]]
name = "jtag"
path = "src/bin/jtag.rs"
test = false
bench = false

[[bin]]
name = "read32"
path = "src/bin/read32.rs"
test = false
bench = false

[[bin]]
name = "write32"
path = "src/bin/write32.rs"
test = false
bench = false

[[bin]]
name = "fence-i-f101"
path = "src/bin/fence_i_f101.rs"
test = false
bench = false

[[bin]]
name = "copy-v821"
path = "src/bin/copy_v821.rs"
test = false
bench = false

[[bin]]
name = "spi-d1"
path = "src/bin/spi_d1.rs"
test = false
bench = false

[[bin]]
name = "spi-f101"
path = "src/bin/spi_f101.rs"
test = false
bench = false

[[bin]]
name = "spi-v821"
path = "src/bin/spi_v821.rs"
test = false
bench = false
